---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb-02
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: unique-volumeid-01  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//smb-server.dev.svc.cluster.local/share"
    nodeStageSecretRef:
      name: smbcreds
      namespace: dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-smb-02
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-smb-02
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iis
  labels:
    app: iis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iis
  template:
    metadata:
      labels:
        app: iis
    spec:
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: pvc-smb-02
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: iis-server
        image: mcr.microsoft.com/windows/servercore/iis
        ports:
        - containerPort: 80
        volumeMounts:
        - name: logs
          mountPath: c:\inetpub\test