---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb-01
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: unique-volumeid  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//smb-server.dev.svc.cluster.local/share"
    nodeStageSecretRef:
      name: smbcreds
      namespace: dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-smb-01
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-smb-01
  storageClassName: ""
